name = resourceMonitor
summary = "Resource Monitor"
description = """A handy resource monitor to report CPU load, memory usage, battery, disk usage status and more."""
author = "Alex Hall <mehgcap@gmail.com>, Joseph Lee <joseph.lee22590@gmail.com>, Kefas lungu <jameskefaslungu@gmail.com>, Beqa Gozalishvili <beqaprogger@gmail.com>, Tuukka Ojala <tuukka.ojala@gmail.com>, Ethin Probst <harlydavidsen@gmail.com> and other NVDA contributors"
url = https://addons.nvda-project.org/
version = 23.0.4
docFileName = readme.html
minimumNVDAVersion = 2022.4
lastTestedNVDAVersion = 2023.1
updateChannel = None
